import type { AppState } from "./types";
import { loadApiKey, loadDecks, loadUserTags } from "./utils/storage";

export const state: AppState = {
	view: "home",
	studyMode: "flashcard",
	mixStudyName: null,
	decks: [],
	activeDeckId: null,
	editDeckId: null,
	cardIndex: 0,
	flipped: false,
	correct: 0,
	wrong: 0,
	missed: [],
	cardQualities: {},
	studyStartTime: 0,
	lastCardSnapshot: null,
	deckPlayCounts: {},
	deckSearch: "",
	deckTagFilter: "",
	userTags: loadUserTags(),
	streak: 0,
	deckDueCounts: {},
	studyCards: null,
	apiKey: loadApiKey(),
	isGenerating: false,
	generationProgress: "",
	user: null,
	duel: null,
	quiz: null,
};
